---
abstract: "A simple client to Wing's web services."
author:
  - 'JT Smith <jt@plainblack.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Wing-Client
requires:
  HTTP::CookieJar: 0.004
  HTTP::Request::Common: 0
  HTTP::Thin: 0
  HTTP::Tiny: 0.034
  JSON: 0
  Moo: 1.002000
  Ouch: 0.0400
  Test::Deep: 0
  Test::More: 0
  URI: 0
resources:
  bugtracker: http://github.com/rizen/Wing-Client/issues
  repository: git://github.com/rizen/Wing-Client.git
version: 0.0401
